server:
  port: 8002

spring:
  application:
    name: product_service
  datasource:
    url: jdbc:postgresql://localhost:5432/kade_products
    username: kade
    password: kade
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
