server:
  port: 8002

spring:
  application:
    name: product_service
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
    time-zone: "UTC"
  datasource:
    url: "jdbc:postgresql://localhost:5433/kade_products"
    username: postgres
    password: "1212"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  cloud:
    gcp:
      project-id: gpstracker-96510
      storage:
        project-id: gpstracker-96510
        credentials:
          location: classpath:config/gpstracker-96510-513e76d88045.json

gcp:
  bucket:
    name: kade_marketplace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
