server:
  port: 8002

spring:
  application:
    name: product_service
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
    time-zone: "UTC"
  datasource:
    url: "jdbc:postgresql://localhost:5432/kade_products"
    username: postgres
    password: "1212"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
